crm/crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from minicrm import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),
    path('admin/', admin.site.urls, name='admin'),
    path('minicrm/', include('minicrm.urls', namespace='minicrm')),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/minicrm/urls.py
from django.urls import path
from minicrm.views import (sidebartest, AgentListView,
 AgentDetailView, ContactListView, AgentCreate,
   MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, IndexPageView, ContactDetailView, 
   ContactCreateView, UserListView, UserDetailView, ContactUpdateView)

app_name = 'minicrm'

urlpatterns = [
    path('', IndexPageView.as_view(), name='index'),
    path('agents/', AgentListView.as_view(), name='agents'),
    path('detail_agent/<int:pk>', AgentDetailView.as_view(), name='detail_agent'),
    path('agents/create', AgentCreate.as_view(), name='create_agent'),
    path('contacts/', ContactListView.as_view(), name='contacts'),
    path('detail_contact/<int:pk>', ContactDetailView.as_view(), name='detail_contact'),
    path('create_contact/', ContactCreateView.as_view(), name='create_contact'),
    path('update_contact/<int:pk>', ContactUpdateView.as_view(), name='update_contact'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('detail_message/<int:pk>', MessageDetailView.as_view(), name='detail_message'),
    path('update_message/<int:pk>', MessageUpdateView.as_view(), name='update_message'),
    path('users/', UserListView.as_view(), name='users'),
    path('detail_user/<int:pk>', UserDetailView.as_view(), name='detail_user'),
    path('sidebartest/', sidebartest, name='sidebartest'),
]

crm/minicrm/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass 

# class ManagerManager(models.Manager):
#     def get_queryset(self):
#         return super().get_queryset().filter()

# class AgentManager(models.Manager):
#     def get_queryset(self, user):
#         return super().get_queryset().get(user = user)


# Create your models here.
class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    agent_phone = models.CharField(max_length=10)
    agent_photo = models.ImageField(null=True, blank=True, upload_to = 'images/')
    agent_levelaccess = models.IntegerField()
     
    def __str__(self):
        return self.user.first_name + ' ' + self.user.last_name

    def get_absolute_url(self):
        return reverse("agent", kwargs={"pk": self.pk})

class Contact(models.Model):
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    contact_firstname = models.CharField(max_length=256)
    contact_lastname = models.CharField(max_length=256)
    contact_email = models.CharField(max_length=256)
    contact_phone = models.CharField(max_length=10)
    contact_phone2 = models.CharField(max_length=10)
    contact_address = models.CharField(max_length=256)
    contact_company = models.CharField(max_length=256)
    contact_vat_no = models.CharField(max_length=9)

    def __str__(self):
        return self.contact_firstname + ' ' + self.contact_lastname

    def get_absolute_url(self):
        return reverse('minicrm:detail_contact', kwargs={'pk': self.pk})

class SoftDeleteManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_deleted=False)


class SoftDeleteModel(models.Model):

    is_deleted = models.BooleanField(default=False)
    obects = models.Manager()
    undeleted_objects = SoftDeleteManager()

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def restore(self):
        self.is_deleted = False
        self.save()

    class Meta:
        abstract = True

class Message(SoftDeleteModel):
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name="contact_message")
    message_title = models.CharField(max_length=256)
    message_content = models.CharField(max_length=1024)
    message_datetime = models.DateTimeField()
    message_channel = models.CharField(max_length=256)
    message_due_date = models.DateField()

    def get_absolute_url(self):
        return reverse('minicrm:detail_message', kwargs={'pk': self.pk})
    
class File(models.Model):
    message = models.ForeignKey(Message, on_delete=models.DO_NOTHING)
    file_name = models.FilePathField()     

crm/minicrm/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from minicrm.models import Agent, User, Contact, Message

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'is_active', 'is_staff', 'is_superuser')
        field_classes = {'username': UsernameField}

class ContactCreationForm(forms.ModelForm):    
    class Meta:
        model = Contact
        exclude = ('agent',)

crm/minicrm/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from minicrm.models import Agent, User, Contact, Message, File
from minicrm.forms import MyUserCreationForm, ContactCreationForm
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def show_logged_in_user(request):
    current_user = request.user
    print(current_user.id)
    print(current_user.username)

def get_logged_in_user(request):
    return request.user


class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = MyUserCreationForm

    def get_success_url(self):
        return reverse('login')

class LandingPageView(TemplateView):
    template_name = 'minicrm/landingpage.html'

class IndexPageView(TemplateView):
    template_name = 'minicrm/index.html'

def login(request):
    if request.method == 'post':
        request.session['agent'] = Agent.objects.get(user = get_logged_in_user(request).pk).pk
    print(request.session['agent'])
    return render(request, 'minicrm/login.html')

def sidebartest(request):
    return render(request, 'minicrm/sidebar.html')

class AgentListView(LoginRequiredMixin, ListView):
    login_url ='/login/'
    redirect_field_name = '/'

    model = Agent

class AgentCreate(LoginRequiredMixin, CreateView):
    model = Agent
    fields ='__all__'
    
    def get_success_url(self):
        return reverse('agents')
    
class ContactListView(LoginRequiredMixin, ListView):
    model = Contact
    redirect_field_name = '/'

class ContactCreateView(LoginRequiredMixin, CreateView):
    template_name = 'minicrm/contact_create.html'
    form_class = ContactCreationForm
        
    def get_success_url(self):
        return reverse('minicrm:contacts')

    def form_valid(self, form):
        user = self.request.user
        form.instance.agent = Agent.objects.get(user = user)
        return super(ContactCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(ContactCreateView, self).get_context_data(*args,**kwargs)
        currentuser = self.request.user
        context['agent'] = Agent.objects.get(user = currentuser.pk)
        return context
    
class ContactDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'contact'
    model = Contact
    template_name = 'minicrm/contact_detail.html'
   
class ContactUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'contact'
    model = Contact
    template_name = 'minicrm/contact_update.html'
    fields = '__all__'


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    redirect_field_name = '/'

class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message
    redirect_field_name = '/'

class MessageUpdateView(LoginRequiredMixin, UpdateView):
    context_object_name = 'message'
    model = Message
    template_name = 'minicrm/message_update.html'
    fields = '__all__'

class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    template_name = 'minicrm/message_create.html'
    fields = '__all__'

# class FileCreateView(CreateView):
#     model = Agent
#     fields = '__all__'

# class FileListView(ListView):
#     model = File

class AgentDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'agent'
    model = Agent
    template_name = 'minicrm/agent_detail.html'

class UserListView(LoginRequiredMixin, ListView):
    login_url ='/login/'
    redirect_field_name = '/'
    model = User

class UserDetailView(LoginRequiredMixin, DetailView):
    context_object_name = 'user'
    model = User
    template_name = 'minicrm/user_detail.html'

crm/minicrm/templates/minicrm/agent_detail.html
<!DOCTYPE html>
{% extends 'minicrm/base.html' %}

{% block title %}
<title>Agent details</title>
{% endblock title %}

{% load static %}
{% block content %}

    <div class="container mx-auto">
        <h2 class="text-start mb-5 ms-2"> {{agent.user.first_name}} {{agent.user.last_name}}</h2>
        <div class="container row mx-auto">
            <div class="col-lg-4 cardview-image mb-5"> 
                <img src="{{agent.agent_photo.url}}" alt="Ann Mann"
                 style= " width:256px; height:256px ">
            </div>
            <ul class="list-group col-sm-8 mb-5">
                <li class="list-group-item"><b> Username: </b> {{agent.user.username}}</li>
                <li class="list-group-item"><b> Email: </b> {{agent.user.email}}</li>
                <li class="list-group-item"><b> phone: </b> {{agent.agent_phone}}</li>
                <li class="list-group-item"><b> Date joined: </b> {{agent.user.date_joined}}</li>
                <li class="list-group-item"><b> Last login: </b> {{agent.user.last_login}}</li>
                <li class="list-group-item"><b> Is Admin: </b>    
                    {% if agent.user.is_superuser %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </li>
                <li class="list-group-item"><b> Is Staff: </b>    
                    {% if agent.user.is_staff %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </li>
                <li class="list-group-item"><b> Is Active: </b>    
                    {% if agent.user.is_active %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </li>
                <li class="list-group-item"> <b>Level Access:</b>  {{agent.agent_levelaccess}} </li>
                <li class="list-group-item">
                    <div class="col-md-12 text-right">
                        <a href="#" class="btn btn-warning">Edit</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    
{% endblock content %}

crm/minicrm/templates/minicrm/agent_form.html
<!DOCTYPE html>

{% extends 'minicrm/base.html' %}

{% block title %}
<title>Create Agent</title>
{% endblock title %}

{% block content %}

<div class="container">
    <h2>New Agent</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="save">
    </form>
</div>

{% endblock content %}

crm/minicrm/templates/minicrm/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href=" {% static 'minicrm/card.css' %} ">
    <link rel="stylesheet" href=" {% static 'minicrm/forms.css' %} ">
    <link rel="stylesheet" href=" {% static 'minicrm/circles.css' %} ">
    {% block title %}
    <title>Document</title>
    {% endblock title %}
</head>
<body>

{% block navbar %}

    <nav class="navbar navbar-expand-lg navbar-dark sticky-top">
      <div class="container-fluid">
        <a id="landing" class="navbar-brand" href=" {% url 'landing' %} ">miniCRM</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a id="home" class="nav-link active" aria-current="page" href=" {% url 'minicrm:index' %} "> Home </a>
            </li>
            <li class="nav-item">
              <a id="users" class="nav-link" href="{% url 'minicrm:users' %}">Users</a>
            </li>
            <li class="nav-item">
              <a id="agents" class="nav-link" href="{% url 'minicrm:agents' %}">Agents</a>
            </li>
            <li class="nav-item">
              <a id="contacts" class="nav-link" href="{% url 'minicrm:contacts' %}">Contacts</a>
            </li>
            <li class="nav-item">
              <a id="messages" class="nav-link" href="{% url 'minicrm:messages' %}">Messages</a>
            </li>
            <li class="nav-item dropdown ms-lg-5">
                <a href="#" class="nav-link dropdown-toggle btn btn-outline-warning" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   Welcome {{request.user.username}}  
                </a>
                <ul class="dropdown-menu bg-danger text-white" aria-labelledby="navbarDropdown">
                  <li>
                    <a href=" {% url 'logout' %} " class="dropdown-item"> Logout </a>
                  </li>
                </ul>
            </li>
            {% else %}
            {% comment %} <li class="nav-item">
              <a href=" {% url 'signup' %} " class="nav-link"> Signup </a>
            </li> {% endcomment %}
            <li class="nav-item">
              <a href=" {% url 'login' %} " class="nav-link"> Login </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

{% endblock navbar %}

    <div class="mt-5">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src=" {% static 'minicrm/links.js' %}"></script>
</body>
</html>

crm/minicrm/templates/minicrm/contact_create.html
<!DOCTYPE html>

{% extends 'minicrm/base.html' %}

{% block title %}
<title>Create Contact</title>
{% endblock title %}

{% block content %}

<div class="container">
    <h2>New Contact</h2>
    <p> Agent: {{request.user.username}}  </p>
    <p> pk: {{agent}} </p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="save">
    </form>

    {% comment %} <form  action="{% url 'minicrm:create_contact' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p> 
            <input type="hidden" id="id_agent" name="agent" required="" value="{{agent}}">
        </p>
        <p>
          <label for="id_contact_firstname">Contact firstname:</label>
          <input type="text" name="contact_firstname" maxlength="256" required="" id="id_contact_firstname">
        </p>
        <p>
            <label for="id_contact_lastname">Contact lastname:</label>
            <input type="text" name="contact_lastname" maxlength="256" required="" id="id_contact_lastname">
        </p> 
        <p>
            <label for="id_contact_email">Contact email:</label>
            <input type="text" name="contact_email" maxlength="256" required="" id="id_contact_email">
        </p>
        <p>
            <label for="id_contact_phone">Contact phone:</label>
            <input type="text" name="contact_phone" maxlength="10" required="" id="id_contact_phone">
        </p>
        <p>
            <label for="id_contact_phone2">Contact phone2:</label>
            <input type="text" name="contact_phone2" maxlength="10" required="" id="id_contact_phone2">
        </p>
        <p>
            <label for="id_contact_address">Contact address:</label>
            <input type="text" name="contact_address" maxlength="256" required="" id="id_contact_address">
        </p>
        <p>
            <label for="id_contact_company">Contact company:</label>
            <input type="text" name="contact_company" maxlength="256" required="" id="id_contact_company">
        </p>
        <p>
            <label for="id_contact_vat_no">Contact vat no:</label>
            <input type="text" name="contact_vat_no" maxlength="9" required="" id="id_contact_vat_no">
        </p>
        <input class="btn btn-primary" type="submit" value="save">
    </form>
</div> {% endcomment %}

{% endblock content %}

crm/minicrm/templates/minicrm/contact_detail.html
<!DOCTYPE html>
{% extends 'minicrm/base.html' %}

{% block title %}
<title>Contact details</title>
{% endblock title %}

{% load static %}
{% block content %}

    <div class="container mx-auto">
        <h2 class="text-start mb-5 ms-2"> {{contact.contact_firstname}} {{contact.contact_lastname}}</h2>
        <div class="container row justify-content-center">
            {% comment %} <div class="col-lg-4 cardview-image mb-5"> 
                <img src="{% static 'images/person1.png' %}" alt="contact icon"
                 style= " width:256px; height:256px ">
            </div> {% endcomment %}
            <ul class="list-group col-sm-8 mb-5">
                <li class="list-group-item"><b> Assigned Agent: </b> {{contact.agent.user.first_name}} {{contact.agent.user.last_name}}</li>
                <li class="list-group-item"><b> Email: </b> {{contact.contact_email}}</li>
                <li class="list-group-item"><b> phone: </b> {{contact.contact_phone}}</li>
                <li class="list-group-item"><b> phone2: </b> {{contact.contact_phone2}}</li>
                <li class="list-group-item"><b> Address: </b> {{contact.contact_address}}</li>
                <li class="list-group-item"><b> Company: </b> {{contact.contact_company}}</li>
                <li class="list-group-item"><b> VAT No: </b> {{contact.contact_vat_no}}   
                <li class="list-group-item">
                    <div class="col-md-12 text-right">
                        <a href="{% url 'minicrm:update_contact' pk=contact.pk %}" class="btn btn-warning">Edit</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="row">
            {{contact.pk}}
        </div>
    </div>
    
{% endblock content %}

crm/minicrm/templates/minicrm/contact_list.html
<!DOCTYPE html>
{% extends 'minicrm/base.html' %}

{% block title %}
<title>Contacts</title>
{% endblock title %}

{% load static %}
{% block content %}

<div class="container justify-content-center">
    <div class="row">
        <div class="col-6 text-start">
            <div class="fs-1 " style="color: rgb(141, 175, 205)"> Contacts </div>
        </div>
        <div class="col-6 text-end">
            <a href=" {% url 'minicrm:create_contact' %} " class="btn btn-outline-primary ms-5 align-bottom">New</a>
        </div>
        <hr class="mb-5"> 
    </div>
</div>
<div class="container justify-content-center mb-5">
    <div class="row g-5">
{% if contact_list %}
{% for contact in contact_list %}
        <div class="col-lg-6 col-sm-12">
            
            <div class="cardview">
                <div class="cardview-image">
                    <img src=" {% static 'minicrm/images/person1.png' %} " alt="photo">
                </div>
                <div class="cardview-content">
                    <div class="cardview-content-title">
                        <h3>  {{contact.contact_firstname}} {{contact.contact_lastname}} </h3>
                    </div>
                    <div class="cardview-content-body"> 
                        <div class="cardview-content-body-text pe-4">
                            {{contact.contact_email}}
                        </div>
                        <div class="cardview-content-btn">
                            <a href="  {% url 'minicrm:detail_contact' pk=contact.pk %} " class="btn btn-outline-primary">view</a>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
{% endfor %}
    </div>
</div>
{% else %}
<p>No contacts yet</p>
{% endif %}



</div>


{% endblock content %}

crm/minicrm/templates/minicrm/index.html
<!DOCTYPE html>
{% extends 'minicrm/base.html' %}

{% block title %}
<title>Index</title>
{% endblock title %}






{% block content %}

{% include 'minicrm/dashboard.html' %}

<div class="container mt-5">
    <div class="alert alert-primary  rounded-0">
        <h4 class="alert-heading">Index Heading</h4>
        <p>Index Content</p>
        <hr>
        <p class="mb-0">Index Description</p>
        <a href=" {% url 'minicrm:agents' %} "> Go to Agents </a>
      </div>
</div>
{% endblock content %}

crm/minicrm/templates/minicrm/landingpage.html
<!DOCTYPE html>
{% extends 'minicrm/base.html' %}

{% load static %}


{% block content %}
<div class="container">
    <div class="h1">Landing Page</div>
    <a href="/admin" class="btn btn-primary btn-lg">Admin</a>
</div>
{% endblock content %}

crm/minicrm/templates/minicrm/message_create.html
<!DOCTYPE html>

{% extends 'minicrm/base.html' %}

{% block title %}
<title>Create Message</title>
{% endblock title %}

{% block content %}

<div class="container">
    <h2>New Message</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="save">
    </form>
</div>

{% endblock content %}

crm/minicrm/templates/minicrm/message_detail.html
<!DOCTYPE html>
{% extends 'minicrm/base.html' %}

{% block title %}
<title>Message</title>
{% endblock title %}

{% load static %}
{% block content %}

    <div class="container mx-auto">
        <h2 class="text-start mb-5 ms-2"> {{contact.contact_firstname}} {{contact.contact_lastname}}</h2>
        <div class="container row justify-content-center">
            <ul class="list-group col-sm-8 mb-5">
                <li class="list-group-item"><b> Contact: </b> {{message.contact.contact_firstname}} {{message.contact.contact_lastname}}</li>
                <li class="list-group-item"><b> Title: </b> {{message.message_title}}</li>
                <li class="list-group-item"><b> Content: </b> {{message.message_content}}</li>
                <li class="list-group-item"><b> Date: </b> {{message.message_datetime}}</li>
                <li class="list-group-item"><b> Channel: </b> {{message.message_channel}} </li>
                <li class="list-group-item"><b> Due Date: </b> {{message.message_due_date}}</li>
                <li class="list-group-item">
                    <div class="col-md-12 text-right">
                        <a href="{% url 'minicrm:update_message' pk=message.pk %}" class="btn btn-warning">Edit</a>
                        <a href="#" class="btn btn-danger">Delete</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="row">
            {{contact.pk}}
        </div>
    </div>
    
{% endblock content %}

crm/minicrm/templates/minicrm/message_update.html
<!DOCTYPE html>

{% extends 'minicrm/base.html' %}

{% block title %}
<title>Update Message</title>
{% endblock title %}

{% block content %}

<div class="container">
    <h2>Update Message</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="save">
    </form>
</div>

{% endblock content %}

crm/minicrm/templates/minicrm/user_detail.html
<!DOCTYPE html>
{% extends 'minicrm/base.html' %}

{% block title %}
<title>Agent details</title>
{% endblock title %}

{% load static %}
{% block content %}

    <div class="container mx-auto">
        <h2 class="text-start mb-5 ms-2"> {{agent.user.first_name}} {{agent.user.last_name}}</h2>
        <div class="container row mx-auto">
            <div class="col-lg-4 cardview-image mb-5"> 
                <img src="{{agent.agent_photo.url}}" alt="Ann Mann"
                 style= " width:256px; height:256px ">
            </div>
            <ul class="list-group col-sm-8 mb-5">
                <li class="list-group-item"><b> Username: </b> {{user.username}}</li>
                <li class="list-group-item"><b> Email: </b> {{user.email}}</li>
                <li class="list-group-item"><b> phone: </b> {{agent_phone}}</li>
                <li class="list-group-item"><b> Date joined: </b> {{user.date_joined}}</li>
                <li class="list-group-item"><b> Last login: </b> {{user.last_login}}</li>
                <li class="list-group-item"><b> Is Admin: </b>    
                    {% if user.is_superuser %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </li>
                <li class="list-group-item"><b> Is Staff: </b>    
                    {% if user.is_staff %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </li>
                <li class="list-group-item"><b> Is Active: </b>    
                    {% if user.is_active %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </li>
                <li class="list-group-item">
                    <div class="col-md-12 text-right">
                        <a href="#" class="btn btn-warning">Edit</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    
{% endblock content %}